import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sidebar } from "./_components/sidebar";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="relative">
          <div className="absolute top-2 left-2">
            <div className="relative">
              <Image
                alt="data-centre"
                src="/data-centre.png"
                height={405}
                width={405}
              />
              <Image
                alt="g-data"
                src="/g-data.png"
                height={180}
                width={180}
                className="absolute top-1/2 left-9 transform  -translate-y-1/2"
              />
            </div>
          </div>
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
